trigger: none
pool: Default

# parameters:
# - name: envorment
#   type: string
#   default: dev
#   values:
#   - dev
#   - qa
#   - prod

# variables:
# - name: workingDir
#   value: envorment/${{ parameters.envorment }}

# - ${{ if eq(parameters.envorment, 'dev') }}:
#   - group: infra-test-july-terraform-dev

# - ${{ if eq(parameters.envorment, 'qa') }}:
#   - group: infra-test-july-terraform-qa

# - ${{ if eq(parameters.envorment, 'prod') }}:
#   - group: infra-test-july-terraform-prod
 

stages:
  - stage:
    displayName: Package install 
    jobs:
      - job: 
        displayName: Agent packege install
        steps:
        - script: sudo apt install unzip -y
        - script: sudo apt install openjdk-17-jdk -y
        - script: sudo apt install python3-pip -y



  - stage: 
    displayName: terraform install
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            backendServiceArm: 'aug-service'
            backendAzureRmResourceGroupName: 'satish-test'
            backendAzureRmStorageAccountName: 'satish112211'
            backendAzureRmContainerName: 'aug-infra-container'
            backendAzureRmKey: 'azure-infrastructure'
        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        - task: tfsec@1
          continueOnError: true
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/terraform'
